language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/shoe_db

node_js:  
  - "8.11.4"

before_script:
  - psql -c 'create database  shoe_db;' -U postgres
  - psql -U postgres -d shoe_db -a -f shoe.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2
